version: '2'
services:
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: nginx
        depends_on:
            - web
        links:
            - web
        ports:
            -  "3000:80"
            -  "80:80"
        volumes_from:
            - web
    web:
        build:
            context: .
            dockerfile: docker/tornado/Dockerfile
        command: python /code/app.py
        volumes:
            - .:/code
        ports:
            -  "3001:3001"
        links:
            - redis
            - db
        depends_on:
            - db
            - redis
    redis:
        image: redis:latest
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
